import './globals.css'
import Header from './header'
import Footer from './footer'
import styles from './page.module.css'
import Head from 'next/head'

  export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }



export default function RootLayout({ children,}: {  children: React.ReactNode }) {

  return (
    <html lang="is">
      <Head>
        <title>{metadata.title}</title>
        <meta name="" content=""></meta>
        <link rel="" href="/favaicon.ico"></link>
      </Head>
      <body>
        <Header/>
          <section className={styles.grid}>
          {children}
          </section>
        <Footer/>
      </body>
    </html>
  )
}