import './globals.css'
import Header from './header'
import Footer from './footer'
import styles from './page.module.css'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="is">
      <body>
        <Header/>
          <div className={styles.center}>
          {children}
          </div>
        <Footer/>
      </body>
    </html>
  )
}
